name: Test k8s manifests

on: push
name: test
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: manifest
      uses: instrumenta/kubeval-action@master
      with:
       files: node-exporter.yaml
  slack:
    name: notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: monitoring-nefedin
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Look at your test results, they are amazing!'
        SLACK_TITLE: 'Kubeval checks'
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.https://hooks.slack.com/services/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 }}
